<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.6</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>org.example</groupId>
	<artifactId>task3</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>task3</name>
	<description>Demo project for Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
		<mapStruct.version>1.5.2.Final</mapStruct.version>
		<mainClass>org.example.task3.Task3Application</mainClass>
		<imageName>testNative</imageName>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.1.0</version>
		</dependency>

		<dependency>
			<groupId>com.networknt</groupId>
			<artifactId>json-schema-validator</artifactId>
			<version>1.0.87</version>
		</dependency>

		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>1.5.2.Final</version>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>${mainClass}</mainClass>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jsonschema2pojo</groupId>
				<artifactId>jsonschema2pojo-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
					<targetPackage>org.example.task3</targetPackage>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapStruct.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<dependency>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>0.2.0</version>
						</dependency>
					</annotationProcessorPaths>
					<compilerArgs>
						<compilerArg>
							-Amapstruct.defaultComponentModel=spring
						</compilerArg>
					</compilerArgs>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M5</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>${mainClass}</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>

<!--			<plugin>-->
<!--				<groupId>org.apache.maven.plugins</groupId>-->
<!--				<artifactId>maven-shade-plugin</artifactId>-->
<!--				<version>3.5.0</version>-->
<!--				<executions>-->
<!--					<execution>-->
<!--						<phase>package</phase>-->
<!--						<goals>-->
<!--							<goal>shade</goal>-->
<!--						</goals>-->
<!--					</execution>-->
<!--				</executions>-->
<!--			</plugin>-->

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.6.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>${mainClass}</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<id>java</id>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>${mainClass}</mainClass>
						</configuration>
					</execution>
					<execution>
						<id>native</id>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>${project.build.directory}/${imageName}</executable>
							<workingDirectory>${project.build.directory}</workingDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>native</id>
			<build>
				<plugins>
<!--					<plugin>-->
<!--						<groupId>org.codehaus.mojo</groupId>-->
<!--						<artifactId>exec-maven-plugin</artifactId>-->
<!--						<version>3.1.1</version>-->
<!--						<executions>-->
<!--							<execution>-->
<!--								<id>java-agent</id>-->
<!--								<goals>-->
<!--									<goal>exec</goal>-->
<!--								</goals>-->
<!--								<configuration>-->
<!--									<executable>java</executable>-->
<!--									<workingDirectory>${project.build.directory}</workingDirectory>-->
<!--									<arguments>-->
<!--										<argument>-classpath</argument>-->
<!--										<classpath/>-->
<!--										<argument>${mainClass}</argument>-->
<!--									</arguments>-->
<!--								</configuration>-->
<!--							</execution>-->
<!--							<execution>-->
<!--								<id>native</id>-->
<!--								<goals>-->
<!--									<goal>exec</goal>-->
<!--								</goals>-->
<!--								<configuration>-->
<!--									<executable>${project.build.directory}/${imageName}</executable>-->
<!--									<workingDirectory>${project.build.directory}</workingDirectory>-->
<!--								</configuration>-->
<!--							</execution>-->
<!--						</executions>-->
<!--					</plugin>-->

<!--					<plugin>-->
<!--						<groupId>org.graalvm.buildtools</groupId>-->
<!--						<artifactId>native-maven-plugin</artifactId>-->
<!--						<version>0.10.3</version>-->
<!--						<extensions>true</extensions>-->
<!--						<executions>-->
<!--							<execution>-->
<!--								<id>build-native</id>-->
<!--								<goals>-->
<!--									<goal>generateResourceConfig</goal>-->
<!--									<goal>compile-no-fork</goal>-->
<!--								</goals>-->
<!--								<phase>package</phase>-->
<!--							</execution>-->
<!--							<execution>-->
<!--								<id>test-native</id>-->
<!--								<goals>-->
<!--									<goal>generateTestResourceConfig</goal>-->
<!--									<goal>test</goal>-->
<!--								</goals>-->
<!--								<phase>test</phase>-->
<!--							</execution>-->
<!--						</executions>-->
<!--						<configuration>-->
<!--							&lt;!&ndash; ... &ndash;&gt;-->
<!--							<fallback>false</fallback>-->
<!--							<agent>-->
<!--								<enabled>true</enabled>-->
<!--							</agent>-->
<!--						</configuration>-->
<!--					</plugin>-->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>3.0.0-M5</version>
					</plugin>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<version>0.10.3</version>
						<extensions>true</extensions>
						<executions>
							<execution>
								<id>test-native</id>
								<goals>
									<goal>generateTestResourceConfig</goal>
									<goal>test</goal>
								</goals>
								<phase>test</phase>
							</execution>
							<execution>
								<id>build-native</id>
								<goals>
									<goal>generateResourceConfig</goal>
									<goal>compile-no-fork</goal>
								</goals>
								<phase>package</phase>
							</execution>
						</executions>
						<configuration>
							<fallback>false</fallback>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
