spring:
  r2dbc:
    url: r2dbc:h2:mem:///demoDb?options=DB_CLOSE_DELAY=-1
    username: root
    password: root
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: hw15-grafana

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.scheduling: DEBUG
