spring.application.name=task12
server.port=8092
#spring.datasource.url=jdbc:h2:mem:task12db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/task12db
spring.r2dbc.schema=public
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres123

logging.file.path=logs


