spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pgdb
    username: pguser
    password: pgpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    user:
      name: admin
      password: pass

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: hw15-grafana

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

